# Generated by Django 3.0.8 on 2020-08-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traincheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalfare', models.FloatField()),
                ('pnr_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookTrain')),
            ],
        ),
    ]
